class CurrencyModel {
  final String flag;
  final String countryCode;
  final String country;
  final String currencyName;
  final String currencyCode;
  final String currencySymbol;

  const CurrencyModel({
    this.flag = '',
    this.countryCode = '',
    this.country = '',
    this.currencyName = '',
    this.currencyCode = '',
    this.currencySymbol = '',
  });

  factory CurrencyModel.fromList(List<String> data) {
    return CurrencyModel(
      flag: data[0],
      countryCode: data[1],
      country: data[2],
      currencyName: data[3],
      currencyCode: data[4],
      currencySymbol: data[5],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'flag': flag,
      'countryCode': countryCode,
      'country': country,
      'currencyName': currencyName,
      'currencyCode': currencyCode,
      'currencySymbol': currencySymbol,
    };
  }

  @override
  String toString() {
    return 'CurrencyModel(flag: $flag, countryCode: $countryCode, country: $country, currencyName: $currencyName, currencyCode: $currencyCode, currencySymbol: $currencySymbol)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CurrencyModel && other.currencyCode == currencyCode;
  }

  @override
  int get hashCode => currencyCode.hashCode;

  static const List<CurrencyModel> currencies = [
    CurrencyModel(flag: "🇦🇫", countryCode: "AF", country: "Afghanistan", currencyName: "Afghan Afghani", currencyCode: "AFN", currencySymbol: "؋"),
    CurrencyModel(flag: "🇦🇱", countryCode: "AL", country: "Albania", currencyName: "Albanian Lek", currencyCode: "ALL", currencySymbol: "L"),
    CurrencyModel(flag: "🇩🇿", countryCode: "DZ", country: "Algeria", currencyName: "Algerian Dinar", currencyCode: "DZD", currencySymbol: "دج"),
    CurrencyModel(flag: "🇦🇩", countryCode: "AD", country: "Andorra", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇦🇴", countryCode: "AO", country: "Angola", currencyName: "Angolan Kwanza", currencyCode: "AOA", currencySymbol: "Kz"),
    CurrencyModel(flag: "🇦🇬", countryCode: "AG", country: "Antigua & Barbuda", currencyName: "East Caribbean Dollar", currencyCode: "XCD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇦🇷", countryCode: "AR", country: "Argentina", currencyName: "Argentine Peso", currencyCode: "ARS", currencySymbol: "\$"),
    CurrencyModel(flag: "🇦🇲", countryCode: "AM", country: "Armenia", currencyName: "Armenian Dram", currencyCode: "AMD", currencySymbol: "֏"),
    CurrencyModel(flag: "🇦🇺", countryCode: "AU", country: "Australia", currencyName: "Australian Dollar", currencyCode: "AUD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇦🇹", countryCode: "AT", country: "Austria", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇦🇿", countryCode: "AZ", country: "Azerbaijan", currencyName: "Azerbaijani Manat", currencyCode: "AZN", currencySymbol: "₼"),
    CurrencyModel(flag: "🇧🇸", countryCode: "BS", country: "Bahamas", currencyName: "Bahamian Dollar", currencyCode: "BSD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇧🇭", countryCode: "BH", country: "Bahrain", currencyName: "Bahraini Dinar", currencyCode: "BHD", currencySymbol: ".د.ب"),
    CurrencyModel(flag: "🇧🇩", countryCode: "BD", country: "Bangladesh", currencyName: "Bangladeshi Taka", currencyCode: "BDT", currencySymbol: "৳"),
    CurrencyModel(flag: "🇧🇧", countryCode: "BB", country: "Barbados", currencyName: "Barbadian Dollar", currencyCode: "BBD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇧🇾", countryCode: "BY", country: "Belarus", currencyName: "Belarusian Ruble", currencyCode: "BYN", currencySymbol: "Br"),
    CurrencyModel(flag: "🇧🇪", countryCode: "BE", country: "Belgium", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇧🇿", countryCode: "BZ", country: "Belize", currencyName: "Belize Dollar", currencyCode: "BZD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇧🇯", countryCode: "BJ", country: "Benin", currencyName: "West African CFA Franc", currencyCode: "XOF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇧🇹", countryCode: "BT", country: "Bhutan", currencyName: "Bhutanese Ngultrum", currencyCode: "BTN", currencySymbol: "Nu"),
    CurrencyModel(flag: "🇧🇴", countryCode: "BO", country: "Bolivia", currencyName: "Bolivian Boliviano", currencyCode: "BOB", currencySymbol: "Bs."),
    CurrencyModel(flag: "🇧🇦", countryCode: "BA", country: "Bosnia & Herzegovina", currencyName: "Bosnia Convertible Mark", currencyCode: "BAM", currencySymbol: "KM"),
    CurrencyModel(flag: "🇧🇼", countryCode: "BW", country: "Botswana", currencyName: "Botswana Pula", currencyCode: "BWP", currencySymbol: "P"),
    CurrencyModel(flag: "🇧🇷", countryCode: "BR", country: "Brazil", currencyName: "Brazilian Real", currencyCode: "BRL", currencySymbol: "R\$"),
    CurrencyModel(flag: "🇧🇳", countryCode: "BN", country: "Brunei", currencyName: "Brunei Dollar", currencyCode: "BND", currencySymbol: "\$"),
    CurrencyModel(flag: "🇧🇬", countryCode: "BG", country: "Bulgaria", currencyName: "Bulgarian Lev", currencyCode: "BGN", currencySymbol: "лв"),
    CurrencyModel(flag: "🇧🇫", countryCode: "BF", country: "Burkina Faso", currencyName: "West African CFA Franc", currencyCode: "XOF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇧🇮", countryCode: "BI", country: "Burundi", currencyName: "Burundian Franc", currencyCode: "BIF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇨🇻", countryCode: "CV", country: "Cabo Verde", currencyName: "Cape Verdean Escudo", currencyCode: "CVE", currencySymbol: "\$"),
    CurrencyModel(flag: "🇰🇭", countryCode: "KH", country: "Cambodia", currencyName: "Cambodian Riel", currencyCode: "KHR", currencySymbol: "៛"),
    CurrencyModel(flag: "🇨🇲", countryCode: "CM", country: "Cameroon", currencyName: "Central African CFA Franc", currencyCode: "XAF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇨🇦", countryCode: "CA", country: "Canada", currencyName: "Canadian Dollar", currencyCode: "CAD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇨🇫", countryCode: "CF", country: "Central African Republic", currencyName: "Central African CFA Franc", currencyCode: "XAF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇹🇩", countryCode: "TD", country: "Chad", currencyName: "Central African CFA Franc", currencyCode: "XAF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇨🇱", countryCode: "CL", country: "Chile", currencyName: "Chilean Peso", currencyCode: "CLP", currencySymbol: "\$"),
    CurrencyModel(flag: "🇨🇳", countryCode: "CN", country: "China", currencyName: "Chinese Yuan Renminbi", currencyCode: "CNY", currencySymbol: "¥"),
    CurrencyModel(flag: "🇨🇴", countryCode: "CO", country: "Colombia", currencyName: "Colombian Peso", currencyCode: "COP", currencySymbol: "\$"),
    CurrencyModel(flag: "🇰🇲", countryCode: "KM", country: "Comoros", currencyName: "Comorian Franc", currencyCode: "KMF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇨🇩", countryCode: "CD", country: "Congo (DRC)", currencyName: "Congolese Franc", currencyCode: "CDF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇨🇬", countryCode: "CG", country: "Congo (Republic)", currencyName: "Central African CFA Franc", currencyCode: "XAF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇨🇷", countryCode: "CR", country: "Costa Rica", currencyName: "Costa Rican Colón", currencyCode: "CRC", currencySymbol: "₡"),
    CurrencyModel(flag: "🇨🇮", countryCode: "CI", country: "Côte d'Ivoire", currencyName: "West African CFA Franc", currencyCode: "XOF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇭🇷", countryCode: "HR", country: "Croatia", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇨🇺", countryCode: "CU", country: "Cuba", currencyName: "Cuban Peso", currencyCode: "CUP", currencySymbol: "\$"),
    CurrencyModel(flag: "🇨🇾", countryCode: "CY", country: "Cyprus", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇨🇿", countryCode: "CZ", country: "Czech Republic", currencyName: "Czech Koruna", currencyCode: "CZK", currencySymbol: "Kč"),
    CurrencyModel(flag: "🇩🇰", countryCode: "DK", country: "Denmark", currencyName: "Danish Krone", currencyCode: "DKK", currencySymbol: "kr"),
    CurrencyModel(flag: "🇩🇯", countryCode: "DJ", country: "Djibouti", currencyName: "Djiboutian Franc", currencyCode: "DJF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇩🇲", countryCode: "DM", country: "Dominica", currencyName: "East Caribbean Dollar", currencyCode: "XCD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇩🇴", countryCode: "DO", country: "Dominican Republic", currencyName: "Dominican Peso", currencyCode: "DOP", currencySymbol: "\$"),
    CurrencyModel(flag: "🇪🇨", countryCode: "EC", country: "Ecuador", currencyName: "United States Dollar", currencyCode: "USD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇪🇬", countryCode: "EG", country: "Egypt", currencyName: "Egyptian Pound", currencyCode: "EGP", currencySymbol: "£"),
    CurrencyModel(flag: "🇸🇻", countryCode: "SV", country: "El Salvador", currencyName: "United States Dollar", currencyCode: "USD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇬🇶", countryCode: "GQ", country: "Equatorial Guinea", currencyName: "Central African CFA Franc", currencyCode: "XAF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇪🇷", countryCode: "ER", country: "Eritrea", currencyName: "Eritrean Nakfa", currencyCode: "ERN", currencySymbol: "Nfk"),
    CurrencyModel(flag: "🇪🇪", countryCode: "EE", country: "Estonia", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇸🇿", countryCode: "SZ", country: "Eswatini", currencyName: "Swazi Lilangeni", currencyCode: "SZL", currencySymbol: "L"),
    CurrencyModel(flag: "🇪🇹", countryCode: "ET", country: "Ethiopia", currencyName: "Ethiopian Birr", currencyCode: "ETB", currencySymbol: "Br"),
    CurrencyModel(flag: "🇫🇯", countryCode: "FJ", country: "Fiji", currencyName: "Fijian Dollar", currencyCode: "FJD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇫🇮", countryCode: "FI", country: "Finland", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇫🇷", countryCode: "FR", country: "France", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇬🇦", countryCode: "GA", country: "Gabon", currencyName: "Central African CFA Franc", currencyCode: "XAF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇬🇲", countryCode: "GM", country: "Gambia", currencyName: "Gambian Dalasi", currencyCode: "GMD", currencySymbol: "D"),
    CurrencyModel(flag: "🇬🇪", countryCode: "GE", country: "Georgia", currencyName: "Georgian Lari", currencyCode: "GEL", currencySymbol: "₾"),
    CurrencyModel(flag: "🇩🇪", countryCode: "DE", country: "Germany", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇬🇭", countryCode: "GH", country: "Ghana", currencyName: "Ghanaian Cedi", currencyCode: "GHS", currencySymbol: "₵"),
    CurrencyModel(flag: "🇬🇷", countryCode: "GR", country: "Greece", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇬🇩", countryCode: "GD", country: "Grenada", currencyName: "East Caribbean Dollar", currencyCode: "XCD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇬🇹", countryCode: "GT", country: "Guatemala", currencyName: "Guatemalan Quetzal", currencyCode: "GTQ", currencySymbol: "Q"),
    CurrencyModel(flag: "🇬🇳", countryCode: "GN", country: "Guinea", currencyName: "Guinean Franc", currencyCode: "GNF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇬🇼", countryCode: "GW", country: "Guinea-Bissau", currencyName: "West African CFA Franc", currencyCode: "XOF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇬🇾", countryCode: "GY", country: "Guyana", currencyName: "Guyanese Dollar", currencyCode: "GYD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇭🇹", countryCode: "HT", country: "Haiti", currencyName: "Haitian Gourde", currencyCode: "HTG", currencySymbol: "G"),
    CurrencyModel(flag: "🇭🇳", countryCode: "HN", country: "Honduras", currencyName: "Honduran Lempira", currencyCode: "HNL", currencySymbol: "L"),
    CurrencyModel(flag: "🇭🇺", countryCode: "HU", country: "Hungary", currencyName: "Hungarian Forint", currencyCode: "HUF", currencySymbol: "Ft"),
    CurrencyModel(flag: "🇮🇸", countryCode: "IS", country: "Iceland", currencyName: "Icelandic Króna", currencyCode: "ISK", currencySymbol: "kr"),
    CurrencyModel(flag: "🇮🇳", countryCode: "IN", country: "India", currencyName: "Indian Rupee", currencyCode: "INR", currencySymbol: "₹"),
    CurrencyModel(flag: "🇮🇩", countryCode: "ID", country: "Indonesia", currencyName: "Indonesian Rupiah", currencyCode: "IDR", currencySymbol: "Rp"),
    CurrencyModel(flag: "🇮🇷", countryCode: "IR", country: "Iran", currencyName: "Iranian Rial", currencyCode: "IRR", currencySymbol: "﷼"),
    CurrencyModel(flag: "🇮🇶", countryCode: "IQ", country: "Iraq", currencyName: "Iraqi Dinar", currencyCode: "IQD", currencySymbol: "ع.د"),
    CurrencyModel(flag: "🇮🇪", countryCode: "IE", country: "Ireland", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇮🇱", countryCode: "IL", country: "Israel", currencyName: "Israeli New Shekel", currencyCode: "ILS", currencySymbol: "₪"),
    CurrencyModel(flag: "🇮🇹", countryCode: "IT", country: "Italy", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇯🇲", countryCode: "JM", country: "Jamaica", currencyName: "Jamaican Dollar", currencyCode: "JMD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇯🇵", countryCode: "JP", country: "Japan", currencyName: "Japanese Yen", currencyCode: "JPY", currencySymbol: "¥"),
    CurrencyModel(flag: "🇯🇴", countryCode: "JO", country: "Jordan", currencyName: "Jordanian Dinar", currencyCode: "JOD", currencySymbol: "د.ا"),
    CurrencyModel(flag: "🇰🇿", countryCode: "KZ", country: "Kazakhstan", currencyName: "Kazakhstani Tenge", currencyCode: "KZT", currencySymbol: "₸"),
    CurrencyModel(flag: "🇰🇪", countryCode: "KE", country: "Kenya", currencyName: "Kenyan Shilling", currencyCode: "KES", currencySymbol: "KSh"),
    CurrencyModel(flag: "🇰🇮", countryCode: "KI", country: "Kiribati", currencyName: "Australian Dollar", currencyCode: "AUD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇰🇵", countryCode: "KP", country: "North Korea", currencyName: "North Korean Won", currencyCode: "KPW", currencySymbol: "₩"),
    CurrencyModel(flag: "🇰🇷", countryCode: "KR", country: "South Korea", currencyName: "South Korean Won", currencyCode: "KRW", currencySymbol: "₩"),
    CurrencyModel(flag: "🇽🇰", countryCode: "XK", country: "Kosovo", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇰🇼", countryCode: "KW", country: "Kuwait", currencyName: "Kuwaiti Dinar", currencyCode: "KWD", currencySymbol: "د.ك"),
    CurrencyModel(flag: "🇰🇬", countryCode: "KG", country: "Kyrgyzstan", currencyName: "Kyrgyzstani Som", currencyCode: "KGS", currencySymbol: "с"),
    CurrencyModel(flag: "🇱🇦", countryCode: "LA", country: "Laos", currencyName: "Lao Kip", currencyCode: "LAK", currencySymbol: "₭"),
    CurrencyModel(flag: "🇱🇻", countryCode: "LV", country: "Latvia", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇱🇧", countryCode: "LB", country: "Lebanon", currencyName: "Lebanese Pound", currencyCode: "LBP", currencySymbol: "ل.ل"),
    CurrencyModel(flag: "🇱🇸", countryCode: "LS", country: "Lesotho", currencyName: "Lesotho Loti", currencyCode: "LSL", currencySymbol: "L"),
    CurrencyModel(flag: "🇱🇷", countryCode: "LR", country: "Liberia", currencyName: "Liberian Dollar", currencyCode: "LRD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇱🇾", countryCode: "LY", country: "Libya", currencyName: "Libyan Dinar", currencyCode: "LYD", currencySymbol: "ل.د"),
    CurrencyModel(flag: "🇱🇮", countryCode: "LI", country: "Liechtenstein", currencyName: "Swiss Franc", currencyCode: "CHF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇱🇹", countryCode: "LT", country: "Lithuania", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇱🇺", countryCode: "LU", country: "Luxembourg", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇲🇬", countryCode: "MG", country: "Madagascar", currencyName: "Malagasy Ariary", currencyCode: "MGA", currencySymbol: "Ar"),
    CurrencyModel(flag: "🇲🇼", countryCode: "MW", country: "Malawi", currencyName: "Malawian Kwacha", currencyCode: "MWK", currencySymbol: "MK"),
    CurrencyModel(flag: "🇲🇾", countryCode: "MY", country: "Malaysia", currencyName: "Malaysian Ringgit", currencyCode: "MYR", currencySymbol: "RM"),
    CurrencyModel(flag: "🇲🇻", countryCode: "MV", country: "Maldives", currencyName: "Maldivian Rufiyaa", currencyCode: "MVR", currencySymbol: "ރ."),
    CurrencyModel(flag: "🇲🇱", countryCode: "ML", country: "Mali", currencyName: "West African CFA Franc", currencyCode: "XOF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇲🇹", countryCode: "MT", country: "Malta", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇲🇭", countryCode: "MH", country: "Marshall Islands", currencyName: "United States Dollar", currencyCode: "USD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇲🇷", countryCode: "MR", country: "Mauritania", currencyName: "Mauritanian Ouguiya", currencyCode: "MRU", currencySymbol: "UM"),
    CurrencyModel(flag: "🇲🇺", countryCode: "MU", country: "Mauritius", currencyName: "Mauritian Rupee", currencyCode: "MUR", currencySymbol: "₨"),
    CurrencyModel(flag: "🇲🇽", countryCode: "MX", country: "Mexico", currencyName: "Mexican Peso", currencyCode: "MXN", currencySymbol: "\$"),
    CurrencyModel(flag: "🇫🇲", countryCode: "FM", country: "Micronesia", currencyName: "United States Dollar", currencyCode: "USD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇲🇩", countryCode: "MD", country: "Moldova", currencyName: "Moldovan Leu", currencyCode: "MDL", currencySymbol: "L"),
    CurrencyModel(flag: "🇲🇨", countryCode: "MC", country: "Monaco", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇲🇳", countryCode: "MN", country: "Mongolia", currencyName: "Mongolian Tögrög", currencyCode: "MNT", currencySymbol: "₮"),
    CurrencyModel(flag: "🇲🇪", countryCode: "ME", country: "Montenegro", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇲🇦", countryCode: "MA", country: "Morocco", currencyName: "Moroccan Dirham", currencyCode: "MAD", currencySymbol: "د.م."),
    CurrencyModel(flag: "🇲🇿", countryCode: "MZ", country: "Mozambique", currencyName: "Mozambican Metical", currencyCode: "MZN", currencySymbol: "MT"),
    CurrencyModel(flag: "🇲🇲", countryCode: "MM", country: "Myanmar", currencyName: "Myanmar Kyat", currencyCode: "MMK", currencySymbol: "K"),
    CurrencyModel(flag: "🇳🇦", countryCode: "NA", country: "Namibia", currencyName: "Namibian Dollar", currencyCode: "NAD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇳🇷", countryCode: "NR", country: "Nauru", currencyName: "Australian Dollar", currencyCode: "AUD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇳🇵", countryCode: "NP", country: "Nepal", currencyName: "Nepalese Rupee", currencyCode: "NPR", currencySymbol: "₨"),
    CurrencyModel(flag: "🇳🇱", countryCode: "NL", country: "Netherlands", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇳🇿", countryCode: "NZ", country: "New Zealand", currencyName: "New Zealand Dollar", currencyCode: "NZD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇳🇮", countryCode: "NI", country: "Nicaragua", currencyName: "Nicaraguan Córdoba", currencyCode: "NIO", currencySymbol: "C\$"),
    CurrencyModel(flag: "🇳🇪", countryCode: "NE", country: "Niger", currencyName: "West African CFA Franc", currencyCode: "XOF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇳🇬", countryCode: "NG", country: "Nigeria", currencyName: "Nigerian Naira", currencyCode: "NGN", currencySymbol: "₦"),
    CurrencyModel(flag: "🇲🇰", countryCode: "MK", country: "North Macedonia", currencyName: "Macedonian Denar", currencyCode: "MKD", currencySymbol: "ден"),
    CurrencyModel(flag: "🇳🇴", countryCode: "NO", country: "Norway", currencyName: "Norwegian Krone", currencyCode: "NOK", currencySymbol: "kr"),
    CurrencyModel(flag: "🇴🇲", countryCode: "OM", country: "Oman", currencyName: "Omani Rial", currencyCode: "OMR", currencySymbol: "﷼"),
    CurrencyModel(flag: "🇵🇰", countryCode: "PK", country: "Pakistan", currencyName: "Pakistani Rupee", currencyCode: "PKR", currencySymbol: "₨"),
    CurrencyModel(flag: "🇵🇼", countryCode: "PW", country: "Palau", currencyName: "United States Dollar", currencyCode: "USD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇵🇦", countryCode: "PA", country: "Panama", currencyName: "Panamanian Balboa", currencyCode: "PAB", currencySymbol: "B/."),
    CurrencyModel(flag: "🇵🇬", countryCode: "PG", country: "Papua New Guinea", currencyName: "Papua New Guinean Kina", currencyCode: "PGK", currencySymbol: "K"),
    CurrencyModel(flag: "🇵🇾", countryCode: "PY", country: "Paraguay", currencyName: "Paraguayan Guaraní", currencyCode: "PYG", currencySymbol: "₲"),
    CurrencyModel(flag: "🇵🇪", countryCode: "PE", country: "Peru", currencyName: "Peruvian Sol", currencyCode: "PEN", currencySymbol: "S/."),
    CurrencyModel(flag: "🇵🇭", countryCode: "PH", country: "Philippines", currencyName: "Philippine Peso", currencyCode: "PHP", currencySymbol: "₱"),
    CurrencyModel(flag: "🇵🇱", countryCode: "PL", country: "Poland", currencyName: "Polish Złoty", currencyCode: "PLN", currencySymbol: "zł"),
    CurrencyModel(flag: "🇵🇹", countryCode: "PT", country: "Portugal", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇶🇦", countryCode: "QA", country: "Qatar", currencyName: "Qatari Riyal", currencyCode: "QAR", currencySymbol: "﷼"),
    CurrencyModel(flag: "🇷🇴", countryCode: "RO", country: "Romania", currencyName: "Romanian Leu", currencyCode: "RON", currencySymbol: "lei"),
    CurrencyModel(flag: "🇷🇺", countryCode: "RU", country: "Russia", currencyName: "Russian Ruble", currencyCode: "RUB", currencySymbol: "₽"),
    CurrencyModel(flag: "🇷🇼", countryCode: "RW", country: "Rwanda", currencyName: "Rwandan Franc", currencyCode: "RWF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇰🇳", countryCode: "KN", country: "Saint Kitts & Nevis", currencyName: "East Caribbean Dollar", currencyCode: "XCD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇱🇨", countryCode: "LC", country: "Saint Lucia", currencyName: "East Caribbean Dollar", currencyCode: "XCD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇻🇨", countryCode: "VC", country: "Saint Vincent & Grenadines", currencyName: "East Caribbean Dollar", currencyCode: "XCD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇼🇸", countryCode: "WS", country: "Samoa", currencyName: "Samoan Tālā", currencyCode: "WST", currencySymbol: "T"),
    CurrencyModel(flag: "🇸🇲", countryCode: "SM", country: "San Marino", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇸🇹", countryCode: "ST", country: "São Tomé & Príncipe", currencyName: "São Tomé & Príncipe Dobra", currencyCode: "STN", currencySymbol: "Db"),
    CurrencyModel(flag: "🇸🇦", countryCode: "SA", country: "Saudi Arabia", currencyName: "Saudi Riyal", currencyCode: "SAR", currencySymbol: "﷼"),
    CurrencyModel(flag: "🇸🇳", countryCode: "SN", country: "Senegal", currencyName: "West African CFA Franc", currencyCode: "XOF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇷🇸", countryCode: "RS", country: "Serbia", currencyName: "Serbian Dinar", currencyCode: "RSD", currencySymbol: "din"),
    CurrencyModel(flag: "🇸🇨", countryCode: "SC", country: "Seychelles", currencyName: "Seychellois Rupee", currencyCode: "SCR", currencySymbol: "₨"),
    CurrencyModel(flag: "🇸🇱", countryCode: "SL", country: "Sierra Leone", currencyName: "Sierra Leonean Leone", currencyCode: "SLE", currencySymbol: "Le"),
    CurrencyModel(flag: "🇸🇬", countryCode: "SG", country: "Singapore", currencyName: "Singapore Dollar", currencyCode: "SGD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇸🇰", countryCode: "SK", country: "Slovakia", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇸🇮", countryCode: "SI", country: "Slovenia", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇸🇧", countryCode: "SB", country: "Solomon Islands", currencyName: "Solomon Islands Dollar", currencyCode: "SBD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇸🇴", countryCode: "SO", country: "Somalia", currencyName: "Somali Shilling", currencyCode: "SOS", currencySymbol: "Sh"),
    CurrencyModel(flag: "🇿🇦", countryCode: "ZA", country: "South Africa", currencyName: "South African Rand", currencyCode: "ZAR", currencySymbol: "R"),
    CurrencyModel(flag: "🇸🇸", countryCode: "SS", country: "South Sudan", currencyName: "South Sudanese Pound", currencyCode: "SSP", currencySymbol: "£"),
    CurrencyModel(flag: "🇪🇸", countryCode: "ES", country: "Spain", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇱🇰", countryCode: "LK", country: "Sri Lanka", currencyName: "Sri Lankan Rupee", currencyCode: "LKR", currencySymbol: "₨"),
    CurrencyModel(flag: "🇸🇩", countryCode: "SD", country: "Sudan", currencyName: "Sudanese Pound", currencyCode: "SDG", currencySymbol: "£"),
    CurrencyModel(flag: "🇸🇷", countryCode: "SR", country: "Suriname", currencyName: "Surinamese Dollar", currencyCode: "SRD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇸🇪", countryCode: "SE", country: "Sweden", currencyName: "Swedish Krona", currencyCode: "SEK", currencySymbol: "kr"),
    CurrencyModel(flag: "🇨🇭", countryCode: "CH", country: "Switzerland", currencyName: "Swiss Franc", currencyCode: "CHF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇸🇾", countryCode: "SY", country: "Syria", currencyName: "Syrian Pound", currencyCode: "SYP", currencySymbol: "£"),
    CurrencyModel(flag: "🇹🇼", countryCode: "TW", country: "Taiwan", currencyName: "New Taiwan Dollar", currencyCode: "TWD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇹🇯", countryCode: "TJ", country: "Tajikistan", currencyName: "Tajikistani Somoni", currencyCode: "TJS", currencySymbol: "SM"),
    CurrencyModel(flag: "🇹🇿", countryCode: "TZ", country: "Tanzania", currencyName: "Tanzanian Shilling", currencyCode: "TZS", currencySymbol: "Sh"),
    CurrencyModel(flag: "🇹🇭", countryCode: "TH", country: "Thailand", currencyName: "Thai Baht", currencyCode: "THB", currencySymbol: "฿"),
    CurrencyModel(flag: "🇹🇱", countryCode: "TL", country: "Timor-Leste", currencyName: "United States Dollar", currencyCode: "USD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇹🇬", countryCode: "TG", country: "Togo", currencyName: "West African CFA Franc", currencyCode: "XOF", currencySymbol: "Fr"),
    CurrencyModel(flag: "🇹🇴", countryCode: "TO", country: "Tonga", currencyName: "Tongan Paʻanga", currencyCode: "TOP", currencySymbol: "T\$"),
    CurrencyModel(flag: "🇹🇹", countryCode: "TT", country: "Trinidad & Tobago", currencyName: "Trinidad & Tobago Dollar", currencyCode: "TTD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇹🇳", countryCode: "TN", country: "Tunisia", currencyName: "Tunisian Dinar", currencyCode: "TND", currencySymbol: "د.ت"),
    CurrencyModel(flag: "🇹🇷", countryCode: "TR", country: "Turkey", currencyName: "Turkish Lira", currencyCode: "TRY", currencySymbol: "₺"),
    CurrencyModel(flag: "🇹🇲", countryCode: "TM", country: "Turkmenistan", currencyName: "Turkmenistani Manat", currencyCode: "TMT", currencySymbol: "T"),
    CurrencyModel(flag: "🇹🇻", countryCode: "TV", country: "Tuvalu", currencyName: "Australian Dollar", currencyCode: "AUD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇺🇬", countryCode: "UG", country: "Uganda", currencyName: "Ugandan Shilling", currencyCode: "UGX", currencySymbol: "Sh"),
    CurrencyModel(flag: "🇺🇦", countryCode: "UA", country: "Ukraine", currencyName: "Ukrainian Hryvnia", currencyCode: "UAH", currencySymbol: "₴"),
    CurrencyModel(flag: "🇦🇪", countryCode: "AE", country: "United Arab Emirates", currencyName: "UAE Dirham", currencyCode: "AED", currencySymbol: "د.إ"),
    CurrencyModel(flag: "🇬🇧", countryCode: "GB", country: "United Kingdom", currencyName: "British Pound Sterling", currencyCode: "GBP", currencySymbol: "£"),
    CurrencyModel(flag: "🇺🇸", countryCode: "US", country: "United States", currencyName: "United States Dollar", currencyCode: "USD", currencySymbol: "\$"),
    CurrencyModel(flag: "🇺🇾", countryCode: "UY", country: "Uruguay", currencyName: "Uruguayan Peso", currencyCode: "UYU", currencySymbol: "\$"),
    CurrencyModel(flag: "🇺🇿", countryCode: "UZ", country: "Uzbekistan", currencyName: "Uzbekistani Som", currencyCode: "UZS", currencySymbol: "лв"),
    CurrencyModel(flag: "🇻🇺", countryCode: "VU", country: "Vanuatu", currencyName: "Vanuatu Vatu", currencyCode: "VUV", currencySymbol: "Vt"),
    CurrencyModel(flag: "🇻🇦", countryCode: "VA", country: "Vatican City", currencyName: "Euro", currencyCode: "EUR", currencySymbol: "€"),
    CurrencyModel(flag: "🇻🇪", countryCode: "VE", country: "Venezuela", currencyName: "Venezuelan Bolívar", currencyCode: "VES", currencySymbol: "Bs.S"),
    CurrencyModel(flag: "🇻🇳", countryCode: "VN", country: "Vietnam", currencyName: "Vietnamese Đồng", currencyCode: "VND", currencySymbol: "₫"),
    CurrencyModel(flag: "🇾🇪", countryCode: "YE", country: "Yemen", currencyName: "Yemeni Rial", currencyCode: "YER", currencySymbol: "﷼"),
    CurrencyModel(flag: "🇿🇲", countryCode: "ZM", country: "Zambia", currencyName: "Zambian Kwacha", currencyCode: "ZMW", currencySymbol: "ZK"),
    CurrencyModel(flag: "🇿🇼", countryCode: "ZW", country: "Zimbabwe", currencyName: "Zimbabwe Gold", currencyCode: "ZiG", currencySymbol: "ZiG"),
  ];
}